# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'to_do_DB.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3

conn = sqlite3.connect('list.db')
c = conn.cursor()

c.execute("""CREATE TABLE  if not exists todo_list(
    list_item text)
    """)

conn.commit()

conn.close()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addItem_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.add_it())
        self.addItem_pushButton.setGeometry(QtCore.QRect(20, 70, 170, 40))
        self.addItem_pushButton.setObjectName("addItem_pushButton")
        self.deleteItem_pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.delete_it())
        self.deleteItem_pushButton_2.setGeometry(QtCore.QRect(210, 70, 170, 40))
        self.deleteItem_pushButton_2.setObjectName("deleteItem_pushButton_2")
        self.clearList_pushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clear_it())
        self.clearList_pushButton_3.setGeometry(QtCore.QRect(400, 70, 170, 40))
        self.clearList_pushButton_3.setObjectName("clearList_pushButton_3")
        self.addItem_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addItem_lineEdit.setGeometry(QtCore.QRect(22, 10, 641, 41))
        self.addItem_lineEdit.setObjectName("addItem_lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 120, 651, 261))
        self.listWidget.setObjectName("listWidget")
        self.DB_pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.save_it())
        self.DB_pushButton_4.setGeometry(QtCore.QRect(580, 70, 91, 40))
        self.DB_pushButton_4.setObjectName("DB_pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.grab_all()

    def grab_all(self):
        conn = sqlite3.connect('list.db')
        c = conn.cursor()
        c.execute("SELECT * FROM  todo_list")
        records = c.fetchall()
        conn.commit()
        conn.close()

        for record in records:
            self.listWidget.addItem(str(record[0]))

    def add_it(self):

        item = self.addItem_lineEdit.text()
        self.listWidget.addItem(item)
        self.addItem_lineEdit.setText("")

    def delete_it(self):
        clicked = self.listWidget.currentRow()
        self.listWidget.takeItem(clicked)

    def clear_it(self):
        self.listWidget.clear()

    def save_it(self):
        conn = sqlite3.connect('list.db')
        c = conn.cursor()

        c.execute('DELETE FROM todo_list;')
        items = []
        for index in range(self.listWidget.count()):
            items.append(self.listWidget.item(index).text())
            c.execute(f'insert into todo_list VALUES("{str(items[index])}")')
        print(items)

        conn.commit()
        conn.close()
        #  pop up
        msg = QMessageBox()
        msg.setWindowTitle("Saved To DB")
        msg.setText("Your list is saved")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do List"))
        self.addItem_pushButton.setText(_translate("MainWindow", "Add Item To List"))
        self.deleteItem_pushButton_2.setText(_translate("MainWindow", "Delete Item From List"))
        self.clearList_pushButton_3.setText(_translate("MainWindow", "Clear The List"))
        self.DB_pushButton_4.setText(_translate("MainWindow", "Save to DB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
